[client]
showSidebarNavigation = false

[theme]
# Primary color.
primaryColor = "#000000"

# Background color.
backgroundColor = "#122A47"

# Secondary background.
secondaryBackgroundColor = "#000000"

# Text color.
textColor = "#FFFFFF"

# Font family
font = "monospace"