[theme]
# Primary color.
primaryColor = "#40b5c4"

# Background color.
backgroundColor = "#003153"

# Secondary background.
secondaryBackgroundColor = "#000000"

# Text color.
textColor = "#FFFFFF"

# Font family
font = "monospace"
